# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'git@github.com:Factual/engine-pods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'EngineBrazeDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for EngineBrazeDemo
    pod "FactualEngineSDK", '~> 5.3.0'
    pod 'Appboy-iOS-SDK', '~> 3.3.1'
    pod "BButton"
end
